name: Django CI/CD Workflow

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.12.2
      DJANGO_SECRET_KEY: your-secret-key
      DEBUG: True

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify database.json
      run: |
        if [ ! -f "webapp/api/database.json" ]; then
          echo "Erreur : database.json introuvable !"
          exit 1
        fi

    - name: Run Django Server Test
      run: |
        python manage.py runserver --noreload & sleep 5
        kill $!

    - name: Run Django Tests
      run: |
        python manage.py test
